var listData3 = [{
	value: '01',
	text: '办贷员',
	children: [{
		value: "001",
		text: "客户受理",
		children: [{
			value: "0001",
			text: "1.征信的签订"
		}, {
			value: "0002",
			text: "2.基础信息的了解"
		}, {
			value: "0003",
			text: "3.通过关键性问题的提问"
		}, {
			value: "0004",
			text: "4.将征信和台账信息传达给客户经理"
		}, {
			value: "0005",
			text: "5.其他情况"
		}]
	}, {
		value: "002",
		text: "资料收集",
		children: [{
			value: "0001",
			text: "1.一次性告知贷款所需的全部资料"
		}, {
			value: "0002",
			text: "2.需亲见客户所提供资料原件"
		}, {
			value: "0003",
			text: "3.客户需对提供资料真实性签字确认"
		}, {
			value: "0004",
			text: "4.办贷经理做好资料收集人的签字确认"
		}, {
			value: "0005",
			text: "5.其他情况"
		}]
	}, {
		value: "003",
		text: "面谈面签",
		children: [{
			value: "0001",
			text: "1.对客户有针对性提问"
		}, {
			value: "0002",
			text: "2.人员身份真实性识别"
		}, {
			value: "0003",
			text: "3.客户签字"
		}, {
			value: "0004",
			text: "4.合同签订"
		}, {
			value: "0005",
			text: "5.其他情况"
		}]
	}, {
		value: "004",
		text: "办理入账",
		children: [{
			value: "0001",
			text: "1.委托入账签订"
		}, {
			value: "0002",
			text: "2．贷款入账"
		}, {
			value: "0003",
			text: "3.其他情况"
		}]
	}, {
		value: "005",
		text: "档案管理",
		children: [{
			value: "0001",
			text: "1.档案整理"
		}, {
			value: "0002",
			text: "2.档案交接"
		}]
	}, {
		value: "006",
		text: "禁令",
		children: [{
			value: "0001",
			text: "1.办贷员禁令"
		}]
	}, {
		value: "007",
		text: "文本",
		children: [{
			value: "0001",
			text: "信贷文本"
		}]
	}, {
		value: "008",
		text: "案例",
		children: [{
			value: "0001",
			text: "4家村行的防范案例（我行）"
		}]
	}]
}, {
	value: '02',
	text: '客户经理',
	children: [{
		value: "001",
		text: "客户营销",
		children: [{
			value: "0001",
			text: "1.了解不同的营销渠道"
		}]
	}, {
		value: "002",
		text: "客户受理",
		children: [{
			value: "0001",
			text: "1.征信的签订"
		}, {
			value: "0002",
			text: "2.基础信息的了解"
		}, {
			value: "0003",
			text: "3.通过关键性问题的提问"
		}]
	}, {
		value: "003",
		text: "外出资料收集",
		children: [{
			value: "0001",
			text: "1.一次性告知贷款所需的全部资料"
		}, {
			value: "0002",
			text: "2.需亲见客户所提供资料原件"
		}, {
			value: "0003",
			text: "3.客户需对提供资料真实性签字确认"
		}, {
			value: "0004",
			text: "4.做好资料收集人的签字确认"
		}]
	}, {
		value: "004",
		text: "非现场调查",
		children: [{
			value: "0001",
			text: "1.征信检查"
		}, {
			value: "0002",
			text: "2.行内系统查询"
		}, {
			value: "0003",
			text: "3.公开信息查询"
		}, {
			value: "0004",
			text: "4.村行要求的其他非现场调查要求。"
		}, {
			value: "0005",
			text: "5.查看客户我行的资金流和其他业务办理情况"
		}, {
			value: "0006",
			text: "6.主要目的"
		}]
	}, {
		value: "005",
		text: "现场调查",
		children: [{
			value: "0001",
			text: "1.对非现场调查信息开展验证"
		}, {
			value: "0002",
			text: "2.了解经营情况、家庭情况"
		}, {
			value: "0003",
			text: "3.了解借款用途"
		}, {
			value: "0004",
			text: "4.对抵押物的排查要点"
		}, {
			value: "0005",
			text: "5.按层级开展调查"
		}, {
			value: "0006",
			text: "6.拍照留底"
		}]
	}, {
		value: "006",
		text: "贷后管理",
		children: [{
			value: "0001",
			text: "非现场贷后检查"
		}, {
			value: "0002",
			text: "现场贷后检查"
		}, {
			value: "0003",
			text: "贷款利息、贷款到期的催收"
		}]
	}, {
		value: "007",
		text: "文本",
		children: [{
			value: "0001",
			text: "各类信贷文本熟悉"
		}]
	}, {
		value: "008",
		text: "操作",
		children: [{
			value: "0001",
			text: "各类系统的操作"
		}]
	}]
}]